server:
  port: 5000
eureka:
  client:
    service-url:
     defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
aliyun:
 oss:
  end-point: 
  bucket-name: 
  access-key-id: 
  access-key-secret: 
  bucket-domain: 
