server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
