server:
  port: 3000
spring:
  application:
    name:  atguigu-crowd-redis
  redis:
    host: 127.0.0.1   #192.168.56.0  虚拟机的ip  #如果redis不在本机就写redis所在电脑的ip地址
eureka:
  client:
    service-url:
     defaultZone: http://localhost:1000/eureka